# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  raytracer_config = debug
endif
ifeq ($(config),release)
  raytracer_config = release
endif

PROJECTS := raytracer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raytracer:
ifneq (,$(raytracer_config))
	@echo "==== Building raytracer ($(raytracer_config)) ===="
	@${MAKE} --no-print-directory -C . -f raytracer.make config=$(raytracer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f raytracer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raytracer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"